version: '3.8'
services:
  express:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express
    ports:
      - 3000:3000
    # map views folder to volume
    volumes:
      - ./views:/app/views
    depends_on:
      - nginx
  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80

  

  


